### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by margaritis** [dudadornelles/flight-control-tower#9]
```
Failures:

  1) match matches all inbound events
   Message:
     Expected [ 'b', 'c', 'click' ] to contain 'd'.
   Stacktrace:
     Error: Expected [ 'b', 'c', 'click' ] to contain 'd'.
    at null.<anonymous> (/Users/breath/Documents/tower/spec/matchSpec.js:35:31)

  2) match matches all inbound events
   Message:
     Expected [ 'b', 'c', 'click' ] to contain 'e'.
   Stacktrace:
     Error: Expected [ 'b', 'c', 'click' ] to contain 'e'.
    at null.<anonymous> (/Users/breath/Documents/tower/spec/matchSpec.js:36:31)

  3) match matches all inbound events
   Message:
     Expected [ 'g' ] to contain 'f'.
   Stacktrace:
     Error: Expected [ 'g' ] to contain 'f'.
    at null.<anonymous> (/Users/breath/Documents/tower/spec/matchSpec.js:40:32)

Finished in 0.012 seconds
2 tests, 10 assertions, 3 failures, 0 skipped
```

**Comment by dudadornelles** [comment]
They are fixed now with some new use cases. Let me know everything works for you now.

**Comment by margaritis** [comment]
:+1: I will check them and i will let you know!
